language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"
install:
  - pip3 install .
before_script:
  - pip3 install python-coveralls
  - pip3 install coverage
script:
  - coverage run --source pylazybam.bam -m pylazybam.tests.test_all
after_success:
  - coveralls
